language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

install:
    - npm install

script:
    - cargo test --verbose
    - npm run build

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
