dist: bionic
addons:
    apt:
        packages:
            - nodejs-dev node-gyp libssl1.0-dev npm

language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
    fast_finish: true

install:
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
    - cd ext-websocket; npm install; cd ..
    - rustup component add clippy

script:
    - cargo test --verbose --workspace
    - cargo test --features cache-multiplication --verbose --workspace
    - cargo check --features "prime-two concurrent" --workspace
    - cargo clippy --workspace --all-targets -- -D warnings
    - cargo clippy --workspace --features "cache-multiplication concurrent" --all-targets -- -D warnings
    - cd ext-websocket; npm run build; cd ..

cache:
    cargo: true
    directories:
        - ext-websocket/node_modules

before_deploy:
    - sh gen_doc.sh
    - cp -r target/doc/ ext-websocket/dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ext-websocket/dist/
  on:
      branch: master
      condition: "$TRAVIS_RUST_VERSION = stable"
