language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

jobs:
    include:
        - stage: Node.js
          install:
              - npm install
              - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
    branch: master
