dist: bionic

language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
    fast_finish: true

install:
    - export PATH="$HOME/bin:$HOME/.cargo/bin:$PATH"
    - cargo install wasm-bindgen-cli
    - ./install-wasm-opt.sh
    - rustup component add clippy
    - git clone --depth 1 https://github.com/SpectralSequences/ext/

script:
    - cargo clippy -- -D warnings
    - ./build.sh

cache:
    cargo: true
    directories:
        - $HOME/bin

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
      branch: master
      condition: "$TRAVIS_RUST_VERSION = stable"
