language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

install:
    - npm install

script:
    - cargo test --verbose
    - npm run build

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
    branch: master
