dist: bionic
language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
    fast_finish: true

install:
    - npm install

script:
    - cargo test --verbose
    - npm run build

cache:
    cargo: true
    directories:
        - node_modules

before_deploy:
    - sh gen_docs.sh
    - cp -r target/doc/ dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
      branch: master
      condition: "$TRAVIS_RUST_VERSION = stable"
