[package]
name = "rust_ext"
version = "0.1.0"
authors = ["Hood <hood@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.2.0"
wasm-bindgen = "0.2"
spin = "0.5.0"

[dev-dependencies]
rand = "0.7.0"
rstest = "0.3.0"
wasm-bindgen-test = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]