[package]
name = "rust_ext"
version = "0.1.0"
authors = ["Hood Chatham <hood@mit.edu>"]
edition = "2018"
description = "Compute Ext over the Steenrod algebra"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.2.0"
wasm-bindgen = "0.2"
spin = "0.5.0"
rental = "0.5.4"
wasm_bindgen_noop = { path = "wasm-bindgen-noop"}

[dev-dependencies]
rand = "0.7.0"
rstest = "0.3.0"
wasm-bindgen-test = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
proc-macro = true


[workspace]
members = ["wasm-bindgen-noop"]