[package]
name = "ext-websocket"
version = "0.1.0"
authors = ["Hood Chatham <hood@mit.edu>", "Dexter Chua <dalcde@yahoo.com.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"
serde_json = "*"
chrono = "*"
serde = { version = "*", features = ["derive"] }
rust_ext = { path = "../" }
bivec = { path = "../bivec" }
enum_dispatch = "0.1.3"
textwrap = { version = "*", features = ["term_size"] }

[features]
cache-multiplication = ["rust_ext/cache-multiplication"]
