[package]
name = "maybe-rayon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = { git = "https://github.com/nhukc/rayon", optional = true }

[features]
default = []
concurrent = ["rayon"]
