[package]
name = "python_utils"
version = "0.1.0"
authors = ["Hood Chatham <hood@mit.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
paste = "0.1"

[dev-dependencies]

[features]

[dependencies.pyo3]
version = "0.10.1"