[package]
name = "fp"
version = "0.1.0"
authors = ["Dexter Chua <dexter@math.harvard.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0.0", optional = true }
serde = { version = "1.0.0", optional = true }
# Cannot upgrade due to https://gitlab.com/antonok/enum_dispatch/-/issues/34
enum_dispatch = "0.2.0"
saveload = { path = "../saveload" }
itertools = "0.9.0"
syn = "=1.0.57"

[dev-dependencies]
rand = "0.7.0"
rstest = "0.6.4"
bencher = "0.1.5"

[features]
default = ["json", "odd-primes"]

odd-primes = []
json = ["serde_json", "serde"]

[[bench]]
name = "bench"
harness = false
