[package]
name = "algebra"
version = "0.1.0"
authors = ["Hood Chatham <hood@mit.edu>", "Dexter Chua <dexter@math.harvard.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
enum_dispatch = "0.2.0"
itertools = "0.9.0"
lazy_static = "1.2.0"
nom = { version = "5.0.0", default-features = false, features = ["alloc"] }
parking_lot = "0.11"
syn = "=1.0.57"


bivec = { path = "../bivec"}
error = { path = "../error" }
fp = { path = "../fp" }
once = { path = "../once" }
query = { path = "../query" }
saveload = { path = "../saveload" }

[dev-dependencies]
rand = "0.7.0"
rstest = "0.5.0"
bencher = "0.1.5"
