name: Test rust_ext

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
        RUST_BACKTRACE: 1
        RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}

    strategy:
      matrix:
          toolchain: ['nightly-2021-02-27', 'nightly']

    steps:
    - uses: actions/checkout@v2

    - name: Cache files
      uses: actions/cache@v2
      with:
          path: |
              ~/.rustup
              ~/.cargo
              **/target
          key: ${{ matrix.toolchain }}-${{ hashFiles('ext/Cargo.*') }}

    - name: Install rustup
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}

    - name: Run tests
      run: make -C ext test

    - name: Run concurrent tests
      run: make -C ext test-concurrent

  examples:
    runs-on: ubuntu-latest
    env:
        RUST_BACKTRACE: 1
        RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}

    strategy:
      matrix:
          toolchain: ['nightly-2021-02-27', 'nightly']
          components: clippy, rustfmt

    steps:
    - uses: actions/checkout@v2

    - name: Cache files
      uses: actions/cache@v2
      with:
          path: |
              ~/.rustup
              ~/.cargo
              **/target
          key: lint-${{ matrix.toolchain }}-${{ hashFiles('ext/Cargo.*', 'rust_webserver/Cargo.*') }}

    - name: Run lint
      run: make -C ext lint

    - name: Lint rust_webserver
      run: make -C rust_webserver lint

  examples:
    runs-on: ubuntu-latest
    env:
        RUST_BACKTRACE: 1
        RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}

    strategy:
      matrix:
          toolchain: ['nightly-2021-02-27', 'nightly']

    steps:
    - uses: actions/checkout@v2

    - name: Cache files
      uses: actions/cache@v2
      with:
          path: |
              ~/.rustup
              ~/.cargo
              **/target
          key: example-${{ matrix.toolchain }}-${{ hashFiles('ext/Cargo.*') }}

    - name: Install rustup
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}

    - name: Run examples
      run: make -C ext run_examples
